-- CreateEnum
CREATE TYPE "Position" AS ENUM ('ALUMNI', 'SISWA', 'MAHASISWA');

-- CreateEnum
CREATE TYPE "Kampus" AS ENUM ('UNIVERSITAS_PALANGKA_RAYA', 'UNIVERSITAS_TERBUKA_PALANGKA_RAYA', 'UNIVERSITAS_KRISTEN_PALANGKA_RAYA', 'UNIVERSITAS_MUHAMMADIYAH_PALANGKA_RAYA', 'UNIVERSITAS_PGRI_PALANGKA_RAYA', 'UNIVERSITAS_SIBER_ASIA_PALANGKA_RAYA', 'IAIN_PALANGKA_RAYA', 'IAKN_PALANGKA_RAYA', 'IAHN_TAMPUNG_PENYANG_PALANGKA_RAYA', 'ITSNU_KALIMANTAN', 'STMIK_PALANGKA_RAYA', 'STIH_TAMBUN_BUNGAI', 'STIP_BUNGA_BANGSA', 'STIE_PALANGKA_RAYA', 'STIE_YBPK', 'STIKES_EKA_HARAP', 'STIPAS_TAHASAK_DANUM_PAMBELUM', 'POLTEKKES_PALANGKA_RAYA', 'AKBID_BETANG_ASI_RAYA', 'OTHER');

-- CreateEnum
CREATE TYPE "Pelayanan" AS ENUM ('MAHASISWA', 'SISWA', 'ALUMNI', 'BPP', 'STAF_ADMIN', 'STAF_SISWA', 'STAF_SISWA_ASC', 'STAF_MAHASISWA', 'STAF_MAHASISWA_ASC', 'OTHER');

-- CreateTable
CREATE TABLE "Employee" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "position" "Position",
    "image" TEXT,
    "kampus" "Kampus",
    "otherKampus" TEXT,
    "jurusan" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "angkatan" INTEGER NOT NULL,
    "birthDay" TEXT,
    "pelayanan" "Pelayanan",
    "otherPelayanan" TEXT,
    "alamat" TEXT,

    CONSTRAINT "Employee_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Employee_email_key" ON "Employee"("email");
