import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
    await prisma.employee.createMany({
        data: [
            {
                id: "1",
                name: "Santi Matondang",
                email: "santimatondang775@gmail.com",
                position: "ALUMNI",
                image: null,
                kampus: "UNIVERSITAS_TERBUKA_PALANGKA_RAYA",
                otherKampus: null,
                jurusan: "S1 - Pendidikan Luar Sekolah",
                createdAt: new Date("2025-01-18T18:57:39.705Z"),
                updatedAt: new Date("2025-01-19T01:56:17.601Z"),
                angkatan: 2020,
                birthDay: "2000-03-22",
                pelayanan: "STAF_ADMIN",
                otherPelayanan: null,
                alamat: "Palangkaraya",
            },
            {
                id: "2",
                name: "Rapeni Itati Nawara",
                email: "rapeniitati@gmail.com",
                position: "SISWA",
                image: null,
                kampus: "UNIVERSITAS_PALANGKA_RAYA",
                otherKampus: null,
                jurusan: "S1 - Teknik Informatika",
                createdAt: new Date("2025-01-18T18:57:39.705Z"),
                updatedAt: new Date("2025-01-18T18:57:39.705Z"),
                angkatan: 2013,
                birthDay: "2002-11-25",
                pelayanan: "STAF_SISWA_ASC",
                otherPelayanan: null,
                alamat: "Palangkaraya",
            },
            {
                id: "3",
                name: "Ivan Perdian",
                email: "ivanperdian@gmail.com",
                position: "ALUMNI",
                image: null,
                kampus: "OTHER",
                otherKampus: "STTB",
                jurusan: "S2 - Magister Teologi",
                createdAt: new Date("2025-01-18T18:57:39.705Z"),
                updatedAt: new Date("2025-01-18T18:57:39.705Z"),
                angkatan: 2010,
                birthDay: "1992-11-25",
                pelayanan: "STAF_MAHASISWA",
                otherPelayanan: null,
                alamat: "Palangkaraya",
            },
            {
                id: "4",
                name: "Siskaevia",
                email: "siskaevia@gmail.com",
                position: "ALUMNI",
                image: null,
                kampus: "OTHER",
                otherKampus: "Udinus",
                jurusan: "S2 - Kesehatan Masyarakat",
                createdAt: new Date("2025-01-18T18:57:39.705Z"),
                updatedAt: new Date("2025-01-18T18:57:39.705Z"),
                angkatan: 2010,
                birthDay: "1992-11-25",
                pelayanan: "BPP",
                otherPelayanan: null,
                alamat: "Palangkaraya",
            },
            {
                id: "5",
                name: "Teki",
                email: "teki@gmail.com",
                position: "ALUMNI",
                image: null,
                kampus: "OTHER",
                otherKampus: null,
                jurusan: null,
                createdAt: new Date("2025-01-18T18:57:39.705Z"),
                updatedAt: new Date("2025-01-18T18:57:39.705Z"),
                angkatan: 2010,
                birthDay: "1992-11-25",
                pelayanan: "BPP",
                otherPelayanan: null,
                alamat: "Palangkaraya",
            },
            {
                id: "6",
                name: "Marvin Setiawan",
                email: "marvinsetiawan@gmail.com",
                position: "ALUMNI",
                image: null,
                kampus: "OTHER",
                otherKampus: "SMA 3 Palangkaraya",
                jurusan: null,
                createdAt: new Date("2025-01-18T18:57:39.705Z"),
                updatedAt: new Date("2025-01-18T18:57:39.705Z"),
                angkatan: 2010,
                birthDay: "1995-01-01",
                pelayanan: "MAHASISWA",
                otherPelayanan: null,
                alamat: "Palangkaraya",
            },
            {
                id: "7",
                name: "Yunia Daya Sintani",
                email: "ybsintani@gmail.com",
                position: "ALUMNI",
                image: null,
                kampus: "IAKN_PALANGKA_RAYA",
                otherKampus: null,
                jurusan: "S1 - Teologi",
                createdAt: new Date("2025-01-18T18:57:39.705Z"),
                updatedAt: new Date("2025-01-18T18:57:39.705Z"),
                angkatan: 2010,
                birthDay: "1995-01-01",
                pelayanan: "OTHER",
                otherPelayanan: "Gereja GKE Palangkaraya",
                alamat: "Palangkaraya",
            }, 
            {
                id: "8",
                name: "Rifan Tinandar",
                email: "rifantinandar@gmail.com",
                position: "MAHASISWA",
                image: null,
                kampus: "UNIVERSITAS_PALANGKA_RAYA",
                otherKampus: null,
                jurusan: "S1 - Manajemen",
                createdAt: new Date("2025-01-18T18:57:39.705Z"),
                updatedAt: new Date("2025-01-18T18:57:39.705Z"),
                angkatan: 2010,
                birthDay: "1995-01-01",
                pelayanan: "MAHASISWA",
                otherPelayanan: null,
                alamat: "Palangkaraya",
            },
            {
                id: "9",
                name: "Dea",
                email: "deapalangkaraya@gmail.com",
                position: "MAHASISWA",
                image: null,
                kampus: "UNIVERSITAS_PALANGKA_RAYA",
                otherKampus: null,
                jurusan: "S1 - Manajemen",
                createdAt: new Date("2025-01-18T18:57:39.705Z"),
                updatedAt: new Date("2025-01-18T18:57:39.705Z"),
                angkatan: 2020,
                birthDay: "1995-01-01",
                pelayanan: "MAHASISWA",
                otherPelayanan: null,
                alamat: "Palangkaraya",
            },
            {
                id: "10",
                name: "Jasmine",
                email: "jasmineptaskalteng@gmail.com",
                position: "MAHASISWA",
                image: null,
                kampus: "UNIVERSITAS_PALANGKA_RAYA",
                otherKampus: null,
                jurusan: "S1 - Manajemen",
                createdAt: new Date("2025-01-18T18:57:39.705Z"),
                updatedAt: new Date("2025-01-18T18:57:39.705Z"),
                angkatan: 2020,
                birthDay: "1995-01-01",
                pelayanan: "SISWA",
                otherPelayanan: null,
                alamat: "Palangkaraya",
            },
            {
                id: "11",
                name: "Yossa",
                email: "yossa@gmail.com",
                position: "MAHASISWA",
                image: null,
                kampus: "UNIVERSITAS_PALANGKA_RAYA",
                otherKampus: null,
                jurusan: "S1 - Teknologi Pendidikan",
                createdAt: new Date("2025-01-18T18:57:39.705Z"),
                updatedAt: new Date("2025-01-18T18:57:39.705Z"),
                angkatan: 2020,
                birthDay: "2001-01-01",
                pelayanan: "SISWA",
                otherPelayanan: null,
                alamat: "Palangkaraya",
            },
        ],
    });

    console.log('Seed data inserted!');
}

main()
    .then(async () => {
        await prisma.$disconnect();
    })
    .catch(async (e) => {
        console.error(e);
        await prisma.$disconnect();
        process.exit(1);
    });
